resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: registry.homelab/redis-operator
  newTag: dev
replacements:
  - source:
      kind: Deployment
      fieldPath: spec.template.spec.containers.[name=manager].image
    targets:
      - select:
          kind: Deployment
        fieldPaths:
          - spec.template.spec.containers.[name=manager].env.[name=OPERATOR_IMAGE].value