package controller

import (
	"testing"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	redisv1 "github.com/MrPickle311/redis-operator/api/v1"
)

// testInstance is a RedisInstance "cache" in namespace "prod" whose ordinal 1
// uses an external PVC; every other ordinal gets a generated one.
var testInstance = &redisv1.RedisInstance{
	ObjectMeta: metav1.ObjectMeta{Name: "cache", Namespace: "prod"},
	Spec: redisv1.RedisInstanceSpec{
		Storage: redisv1.StorageSpec{
			ExistingClaims: []redisv1.ExistingClaim{{InstanceOrdinal: 1, ClaimName: "restored-pvc"}},
		},
	},
}

func TestPodFQDN(t *testing.T) {
	for ordinal, want := range map[int32]string{
		0: "cache-0.cache-hl.prod.svc",
		2: "cache-2.cache-hl.prod.svc",
	} {
		if got := podFQDN(testInstance, ordinal); got != want {
			t.Errorf("podFQDN(%d) = %q, want %q", ordinal, got, want)
		}
	}
}

func TestPVCName(t *testing.T) {
	tests := []struct {
		name         string
		ordinal      int32
		wantName     string
		wantExternal bool
	}{
		{"generated by the operator", 0, "cache-0-data", false},
		{"external from existingClaims", 1, "restored-pvc", true},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			name, external := pvcName(testInstance, tt.ordinal)
			if name != tt.wantName || external != tt.wantExternal {
				t.Errorf("pvcName(%d) = (%q, %v), want (%q, %v)",
					tt.ordinal, name, external, tt.wantName, tt.wantExternal)
			}
		})
	}
}
