apiVersion: redis.operator.com/v1
kind: RedisInstance
metadata:
  labels:
    app.kubernetes.io/name: redis-operator
    app.kubernetes.io/managed-by: kustomize
  name: my-redis
spec:
  instances: 3
  image: redis:7.4
  storage:
    size: 1Gi
